// export default [{ src: "2018-12.jpeg",text: "this is s text" }];

// export default Array.from({ length: 36 }, (v, index) => ({ src: "2018-12.jpeg", brief: "迪士尼", text: "this is s text" + index }));
export default [
  { src: "/src/assets/合照3.jpeg", brief: "第一张自拍", text: "" },
  { src: "/src/assets/合照4.jpeg", brief: "小许的pyq", text: "" },
  { src: "/src/assets/机场分别.jpeg", brief: "机场的分别", text: "" },
  { src: "/src/assets/合照1.jpeg", brief: "来深圳啦", text: "" },
//   { src: "/src/assets/长怡花园.jpeg", brief: "长怡花园", text: "" },
  { src: "/src/assets/合照5.jpeg", brief: "出游合照", text: "" },
  { src: "/src/assets/深大合照.jpeg", brief: "深大合照", text: "" },
  { src: "/src/assets/结婚照（假.jpeg", brief: "结婚照（假", text: "" },
  { src: "/src/assets/文殊院.jpeg", brief: "文殊院", text: "" },
  { src: "/src/assets/九眼桥.jpeg", brief: "九眼桥", text: "" },
  { src: "/src/assets/小许的20岁.jpeg", brief: "小许的20岁", text: "" },
  { src: "/src/assets/香港海洋公园.jpeg", brief: "香港海洋公园", text: "" },
  { src: "/src/assets/天府广场.jpeg", brief: "天府广场", text: "" },
  { src: "/src/assets/笔架山合照.jpeg", brief: "笔架山合照", text: "" },
  { src: "/src/assets/万科云城.jpeg", brief: "万科云城", text: "" },
  { src: "/src/assets/夜色很美.jpeg", brief: "夜色很美", text: "" },
  { src: "/src/assets/灯光秀合照.jpeg", brief: "灯光秀合照", text: "" },
  { src: "/src/assets/肠胃炎.jpeg", brief: "肠胃炎", text: "" },
  { src: "/src/assets/试衣镜合照4.jpeg", brief: "试衣镜合照4", text: "" },
  { src: "/src/assets/笔架山公园.jpeg", brief: "笔架山公园", text: "" },
  { src: "/src/assets/教室的背景.jpeg", brief: "教室的背景", text: "" },
  { src: "/src/assets/新秀.jpeg", brief: "新秀", text: "" },
  { src: "/src/assets/试衣镜1.jpeg", brief: "试衣镜1", text: "" },
  { src: "/src/assets/看展出的我们.jpeg", brief: "看展出的我们", text: "" },
  { src: "/src/assets/试衣镜合照3.jpeg", brief: "试衣镜合照3", text: "" },
  { src: "/src/assets/超市的合照.jpeg", brief: "超市的合照", text: "" },
  { src: "/src/assets/合照2.jpeg", brief: "合照2", text: "" },
  { src: "/src/assets/学校的合影.jpeg", brief: "学校的合影", text: "" },
  { src: "/src/assets/华强北合照.jpeg", brief: "华强北合照", text: "" },
  { src: "/src/assets/地铁反光镜.jpeg", brief: "地铁反光镜", text: "" },
  { src: "/src/assets/试衣镜合照2.jpeg", brief: "试衣镜合照2", text: "" },
  { src: "/src/assets/跨年合照.jpeg", brief: "跨年合照", text: "" },
  { src: "/src/assets/圣诞合照.jpeg", brief: "圣诞合照", text: "" },
  { src: "/src/assets/迪士尼.jpeg", brief: "迪士尼", text: "" },
  { src: "/src/assets/无锡的视频.jpeg", brief: "无锡的视频", text: "" },
  { src: "/src/assets/西安之旅.jpg", brief: "西安之旅", text: "" },
  { src: "/src/assets/杭州之旅.jpg", brief: "杭州之旅", text: "" },
];
